src/main/java/com/apollocurrency/aplwallet/apl/Apl.java
src/main/java/com/apollocurrency/aplwallet/apl/Constants.java
src/main/java/com/apollocurrency/aplwallet/apl/env/CommandLineMode.java
src/main/java/com/apollocurrency/aplwallet/apl/env/DesktopMode.java
src/main/java/com/apollocurrency/aplwallet/apl/env/RuntimeMode.java
src/main/java/com/apollocurrency/aplwallet/apl/http/API.java
src/main/java/com/apollocurrency/aplwallet/apl/mint/MintWorker.java
src/main/java/com/apollocurrency/aplwallet/apl/peer/Peers.java
src/main/java/com/apollocurrency/aplwallet/apldesktop/DesktopApplication.java

Using ServerSocket to capture (api, api-ssl, peer) ports and check availability. If error occurred while capturing port, javafx error alert will be shown. After that app will be closed automatically.
Moved port constants from Peers and API classes to Constants to prevent
static block initialization. Added logging of event and port error in
cmd mode.

APL-355 - Add error alert if api or peer port is busy

---

src/main/java/com/apollocurrency/aplwallet/apl/TwoFactorAuthServiceImpl.java

All apple devices cannot read otpauth url if it contains whitespaces
even if whitespaces were url encoded like %20

Fix 2fa qrcode reading on iphone

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/API.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeerHttpServer.java
apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/UPnP.java

This is small fix of UPnP only. New code checks whenever required port is free and if it is free, uses it. If port is already busy it increments number an tries again. This patch fixes at least work of Apollo with UPnP routers. Now multiple Apollo instances do not "fight" for the same port. The same with API.
This patch does not fix P2P transport and announcements because old code uses IP address only. So full fix will be added to "feature/APL-540-node-id" where P2P transport is already refactored.

UPnP fix: use next free port if desired mapping is already busy

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/Shuffling.java

This is simplified version, which will invalidate cache during popOff to guarantee data consistency, because we cannot restore state under long popOff without store full copies of data after each update

Invalidate cache after popOff

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeerImpl.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/transaction/Data.java

we have to accept unresolvable by DNS peer hosts because is is reversed zone and it is often unset

fix of announced address of unresolveble by DNS hosts

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeerImpl.java

separate monitor for upload/dowload voulme to avoid uneccesary locks; send() is reentrant so it is not synchronized now. Forks a bit faster

better sync of PeerImpl method after some profiling

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/post/CreateTransaction.java

This chfnge fixes exceptions in UI API processing. These exception are being caught in APISErvlet code and error message for UI is formed.
So if you want to catch some  APLException instance you should put error in json of responce.
This fix may affect some work done after Aug 2, 2019 so please verify your code

APL-876 fix exception eating and missing error display on UI

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/shards/ShardInfoDownloader.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/shards/ShardsDownloadService.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/rest/service/TransportInteractionWebSocket.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/files/shards/ShardInfoDownloaderTest.java

Some logging added
Smaller time for secure transport waiting (300 ms)

Better weighting, now 1.0 for last shard with all nodes OK

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/eth/web3j/ComparableStaticGasProvider.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/exchange/service/DexSmartContractService.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/exchange/service/DexSmartContractServiceTest.java

Fix 'nonce too low' problem for previously created but not sent eth transactions

Fix 'nonce too low' for already created eth transactions

---

apl-exec/src/main/java/com/apollocurrency/aplwallet/apl/exec/Apollo.java
apl-exec/src/main/java/com/apollocurrency/aplwallet/apl/exec/CmdLineArgs.java
apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/cdi/AplContainerBuilder.java

Added command line parameter --disable-weld-concurrent-deployment to disable Weld concurrent deployment support. It's very helpful when the application is stuck during the Weld Container building.

disable Weld concurrent deployment support;

---

apl-core/pom.xml
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/transaction/DigitalGoods.java
apl-utils/pom.xml
apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/Search.java

Apache tika was used to MIME type detection only. Replaces by standard jdk classes available since JDK7
javax.el API commented out. It is not used in code. Slight doubts exist that I is may be used in runtime by validators

Apache Tika replaced by lightweight calls to JDK standard classes

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/API.java

WebUI is being searched in ../apollo-web-ui also, so now no symlink is needed in the default installation

WebUI search fixed, no symlink is needed after installation

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/TimeTraceDecoratedThreadPoolExecutor.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/signature/SignatureToolFactory.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/transaction/TransactionUtils.java
apl-exec/src/main/java/com/apollocurrency/aplwallet/apl/exec/Apollo.java

Please do not use private constructors, use package-private. Weld CDI can not start in development mode in that case.

Fix of run in Weld CDI development mode

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/state/account/AccountService.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/state/account/impl/AccountServiceImpl.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/transaction/TransactionApplier.java

Recipient account should be saved during applying transaction as it was in 1.44.7 version (addOrGetAccount method was calling here)

APL-1843 - Fix recipient save during TransactionApplier.apply for recipientId != 0

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/transaction/common/TxSerializerV1Impl.java

Fullsize for Prunable attachments also includes their 'prunable' data size, but Transaction.transactionBytes do not include this

APL-1867 - Fix incorrect payload size calculation during Transaction-to-bytes serialization

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/dao/blockchain/TransactionDaoImpl.java
apl-db-updater/src/main/resources/db/migration/apl/V1_2__enlarge_prunable_json_column.sql

Default text format allows up to 64kb, but serialized to JSON file of 40/42kb size does not fit this restriction

APL-1896 Enlarge unconfirmed_transaction.prunable_json column text->longtext

---

apl-conf/src/main/resources/conf-tn1/apl-blockchain.properties
apl-conf/src/main/resources/conf-tn2/apl-blockchain.properties
apl-conf/src/main/resources/conf-tn3/apl-blockchain.properties
apl-conf/src/main/resources/conf/apl-blockchain.properties
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/AplHealthLogger.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/BlockchainImpl.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/MemPool.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/MemPoolInMemoryState.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/TransactionProcessorImpl.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/UnconfirmedTransactionProcessingService.java

- Optimize the BlockchainImpl.getTransactionHeight method speed
- Limit the number of referenced transactions inside the mempool

APL-1900 Fix/apl 1900 slow forging

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/KeyStoreController.java

Need to  rename because of 'Security2FAInterceptor' incorrect behavior

APL-1886 Fix passphrase parameter's naming

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/cache/RemovedTxsCacheConfig.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/MemPool.java

Fix ArrayIndexOutOfBoundsException. Guava's Cache.asMap doesn't guarantee consistency for an iterator when the cache is under concurrent changes

APL-1922 - Replace Cache.asMap  streaming with arraylist streaming

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/blockchain/TransactionImpl.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/converter/db/UnconfirmedTransactionEntityToModelConverter.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/BlockchainProcessorImpl.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/UnconfirmedTransactionCreator.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/transaction/TransactionUtils.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/transaction/TransactionValidator.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/app/TransactionProcessorTest.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/blockchain/TransactionImplTest.java

Fix transaction size calculation (derived from master's branch version), reason: fullSize for prunable attachments differs depending on data existence, so that getFullSize of Prunable attachments should be used when calculating payload size for consensus purposes <div>Add javadoc
[Changes reviewed on CodeStream](https://api.codestream.com/r/YJQEr_F-aATlXG_8/a_ApC4VpTXuEv_5otCz6Kg?src=GitHub) by ylarin, alzinchenko on May 13, 2021
<sup> Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&amp;utm_medium=pr&amp;utm_campaign=github*com)</sup></div>

Fix: APL 1941-payload-size-mismatch-tn1

---

apl-db-updater/src/main/resources/db/migration/apl/V1_3__enlarge_dex_operation_details_column.sql

[Changes reviewed on CodeStream](https://api.codestream.com/r/YJQEr_F-aATlXG_8/Li9eM4bCQHO2ICUkxlhz1A?src=GitHub) by alzinchenko on May 25, 2021

Fix: APL 1967-dex-operation-details-column-insufficient-size

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/BlockchainProcessorImpl.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/MemPool.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/TransactionProcessorImpl.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/MemPoolTest.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/TransactionProcessorTest.java

The issue was related to the removedTx cache, which counted transaction as removed after first block pushed with it, after that, there was no possibility to create block with this transaction on the node during the following 10 minutes, what lead to the those transactions dismissing on the high forkable network

Fix missing transactions issue on forks

---

apl-api/src/main/java/com/apollocurrency/aplwallet/api/dto/DexCurrencyDTO.java
apl-api/src/main/java/com/apollocurrency/aplwallet/api/dto/WalletDTO.java
apl-api/src/main/java/com/apollocurrency/aplwallet/api/dto/account/CurrenciesWalletsDTO.java
apl-api/src/main/java/com/apollocurrency/aplwallet/api/dto/account/CurrencyWalletsDTO.java
apl-conf/src/main/resources/conf-tn2/chains.json
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/HttpParameterParserUtil.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/AccountController.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/KeyStoreController.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/rest/converter/HttpRequestToCreateTransactionRequestConverterTest.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/AbstractEndpointTest.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/AccountControllerTest.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/Error.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/KeyStoreControllerTest.java
apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/exception/ApiErrors.java
apl-vault-wallet/src/main/java/com/apollocurrency/aplwallet/vault/rest/converter/WalletKeysConverter.java
pom.xml

Fix /keyStore/accountInfo and /accounts/account endpoint responses, lower sharding height for tn2, add new mockito version bom

APL-2086 -  Fix accountInfo response format

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/runnable/GetMoreBlocksJob.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/exception/AplBlockException.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/exception/AplBlockPayloadSizeMismatchException.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/exception/AplBlockTotalAmountMismatchException.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/model/TxsVerificationResult.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/BlockchainProcessorImpl.java

* Introduce AplBlockException hierarchy to replace BlockNotAcceptedException
* Introduce 3 generation attempts for new block with unknown number of failed transactions with overriding total block amount and payload size depending on the appearance of the failed transactions
* Add AplBlockException handling, same as for BlockNotAcceptedException
* Ensure state independence between block generation attempts
* TODO in future: replace 3-attempts generation algorithm by a refactored block generation strategy

APL-2093 - Fix incorrect initial block amount and total payload size during generation with failed txs.

---

apl-api/src/main/java/com/apollocurrency/aplwallet/api/dto/BlockDTO.java
apl-api/src/main/java/com/apollocurrency/aplwallet/api/dto/TxErrorHashDTO.java
apl-conf/src/main/resources/conf-tn2/chains.json
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/AplCore.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/exception/AplBlockTxErrorResultsMismatchException.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/JSONData.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/model/Block.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/model/BlockImpl.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/model/TxErrorHash.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/rest/converter/BlockConverter.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/BlockchainProcessorImpl.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/FailedTransactionVerificationService.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/transaction/common/AbstractTxSerializer.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/exception/AplBlockTxErrorResultsMismatchExceptionTest.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/model/TxErrorHashTest.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/BlockControllerTest.java
apl-exec/src/main/java/com/apollocurrency/aplwallet/apl/exec/Apollo.java

* Lower number of generation attempts with failed txs to 2.
* First generation iteration includes a list of already failed by validation transactions to lower number of generation failure at first iteration
* Block now contains tx error hashes with tx ids (signed by the block generator), so that every node after txs execution can verify its results with the declared by the block generator and fail immediately, when it differs
* Block api responses updated to show number of failed txs in the block and its error hashes,
* FailedTransactionVerificationService is initialized before TaskDispatchManager to perform back up failed txs verification operations (just in case of programming errors)
* Update tn2 config to reset db for testing
<sup> Created from JetBrains using …

APL-2093 - Add consensus for failed txs verification

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/observer/ShufflerObserver.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/state/ShufflerServiceImpl.java

Add AplAcceptableTransactionValidationException catch statement with set of the Shuffler failedTx and and cause to provide the ability on startShuffler endpoint - throw an error with validation cause instead of silently adding invalid shuffler with no registration tx sent
[Changes reviewed on CodeStream](https://api.codestream.com/r/YJQEr_F-aATlXG_8/lAeOVx7aQumsJU63qgT_hA?src=GitHub) by alzinchenko on Oct 13, 2021

APL-2108 - Add handling of the shuffling validation error

---

apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/cdi/transaction/JdbiHandleFactory.java
apl-utils/src/test/java/com/apollocurrency/aplwallet/apl/util/cdi/transaction/JdbiHandleFactoryTest.java

Handle should be removed from the ThreadLocal variable in any case to ensure, than old even broken handle will not be used for other sql queries

APL-2113 - Fix closing of the JDBI handle when error occurs

---

apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/dao/blockchain/TransactionDao.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/dao/blockchain/TransactionDaoImpl.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/db/DatabaseManagerImpl.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/BlockEventSourceProcessor.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/get/GetBlockchainTransactions.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/get/GetPrivateBlockchainTransactions.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/model/Sort.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/Blockchain.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/BlockchainImpl.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/TransactionService.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/TransactionServiceImpl.java
apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/shard/ShardManagement.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/dao/blockchain/TransactionDaoTest.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/db/DatabaseManagerTest.java
apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/BlockchainTest.java
apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/db/TransactionalDataSource.java

Motivation: for  APL Payment txs processing
* Keep a default desc sort
* Add new Sort option (ASC or DESC)
* Update test
Created from JetBrains using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)

APOLLO-26 - Add sort for getBlockchainTransactions request
