ApolloFoundation/Apollo

- html/www/js/nrs.encryption.js
- html/www/js/nrs.forms.js
- html/www/js/nrs.transactions.js
Reverts ApolloFoundation/Apollo#42
> Revert "APL-54 - Removed debug logging"

- html/www/js/nrs.transactions.js
- html/www/js/util/converters.js
Reverts ApolloFoundation/Apollo#67
> Revert "Fixed account ledger pagination"

- html/www/js/nrs.console.js
Reverts ApolloFoundation/Apollo#131
> Revert "APL-127 - Disabled javascript logs"

- src/main/java/com/apollocurrency/aplwallet/apl/http/GetConstants.java
Old wallet web-interface doesnt work properly with this version of GetConstants api
> APL-462 - Add changeable constants to GetConstants API response

- conf/apl-default.properties
- conf/apl.properties
- src/main/java/com/apollocurrency/aplwallet/apl/AplDbVersion.java
- src/main/java/com/apollocurrency/aplwallet/apl/Attachment.java
- src/main/java/com/apollocurrency/aplwallet/apl/BlockImpl.java
- src/main/java/com/apollocurrency/aplwallet/apl/Constants.java
- src/main/java/com/apollocurrency/aplwallet/apl/Currency.java
- src/main/java/com/apollocurrency/aplwallet/apl/FundingMonitor.java
- src/main/java/com/apollocurrency/aplwallet/apl/TransactionImpl.java
- src/main/java/com/apollocurrency/aplwallet/apl/db/FullTextTrigger.java
- src/main/java/com/apollocurrency/aplwallet/apl/http/BroadcastTransaction.java
- src/main/java/com/apollocurrency/aplwallet/apl/http/SendTransaction.java
- src/main/java/com/apollocurrency/aplwallet/apl/http/SetLogging.java
- src/main/java/com/apollocurrency/aplwallet/apl/peer/PeerWebSocket.java
- src/main/java/com/apollocurrency/aplwallet/apl/tools/CompactDatabase.java
- src/main/java/com/apollocurrency/aplwallet/apl/tools/ConstantsExporter.java
- src/main/java/com/apollocurrency/aplwallet/apldesktop/DesktopApplication.java
> APL-465 - Rename attachment, block, currency, transaction variables and db columns

- src/main/java/com/apollocurrency/aplwallet/apl/http/API.java
- src/main/java/com/apollocurrency/aplwallet/apl/http/APIErrorHandler.java
> APL-468 Integrate new UI into desktop wallet

- pom.xml
> APL-492_compile-arm-build-without-javaFx

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/AplCore.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/API.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/rest/filters/ApiSplitFilter.java
Rest API init is called first before all other stuff
> HTTP/rest API starting as early as possible

- apl-desktop/pom.xml
Add Javafx libs for all platforms
> Apl 531 - Add Javafx libs for all platforms

- api-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/ErrorAPI.java
- api-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/TestBase.java
- api-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/tests/TestAssetExchangeAPI.java
getAskOrderIds
getAskOrder + getAskOrderIds
> Asset API automation tests

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/APIErrorHandler.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/APIServlet.java
Reverts ApolloFoundation/Apollo#317
> Revert "Forward to index.html in case handler not found."

- apl-exec/src/main/java/com/apollocurrency/aplwallet/apl/exec/webui/WebUiExtractor.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/Zip.java
zip with constant content (hash) implemented.
> zip implemented

- apl-api/src/main/java/com/apollocurrency/aplwallet/api/p2p/PeerInfo.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeerClient.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeerImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/Peers.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/endpoint/GetInfo.java
It is not a fix itself, but changes which can help find a problem later
> updated PeerInfo and related code

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/TrimService.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/phasing/dao/PhasingPollTable.java
fix getActivePhasingTransactions (ignore phasings created before snapshot block
but finished at height <= snapshot block height
> Fix trim height synchronization (update lastTrimHeight after trim)

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeerImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/Peers.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/shard/observer/ShardObserverTest.java
- websocket closing + unit test enabled
> fixed WebSocket connection leak

- bin/apl-common.sh
- bin/apl-run.bat
- bin/apl-run.sh
- bin/apl-start.sh
JVM option -Xms700m
Also Windows' apl-start.bat corrected to pass command line arguments to java
> Minimum memory requirements for *nix systems set to 700M using -Xms700m

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeerImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/Peers.java
> yet another ClosedChannelException case

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeerImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeerServlet.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/Peers.java
> fix of peer websocekt connection

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/account/Account.java
Revert recent changes (shard initial block cannot have same effective balance properties such as genesis block_
> Fix effective balance calculation

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/FileDownloader.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeerImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeerServlet.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeerWebSocket.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/ChunkedFileOps.java
> read-write locking and code structurization of file downloader

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/JettyConnectorCreator.java
Notghing speclial, just removed misleading logs and added right ones
> fix of API ssl creation log, logging alias of keystore

- pom.xml
weld, jdbi3, resteasy, swagger
> update of few java dependencies

- apl-conf/src/main/resources/conf-tn2/apl-blockchain.properties
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/BlockchainImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/db/DatabaseManager.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/db/DatabaseManagerImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/shard/ShardManagement.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/db/DatabaseManagerTest.java
- shard Data sources are cached by cache with Eviction now
> added DataSource cache, data source shard iteration, unit tests

- apl-core/pom.xml
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/APIEnum.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/NetworkControllerTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/ShardControllerTest.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/env/config/AbstractConfigLoader.java
- pom.xml
increased versions: 
- RestEasy up to 4.3.0; 
- swagger up to 2.0.9;
- jackson up to 2.10.0.pr2;
fixed tests;
> APL-828 increased the RestEasy version up to 4.3.0; fixed tests;

- apl-core/pom.xml
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/cache/AplCacheConfig.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/cache/PublicKeyCacheConfig.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/cache/ShardDsCacheConfigurator.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/cache/CentralizedCacheIntegrationTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/cache/UnifiedCacheIntegrationTest.java
- apl-utils/pom.xml
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/cache/AbstractCacheConfigurator.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/cache/CacheConfiguration.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/cache/CacheConfigurator.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/cache/CacheProducer.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/cache/CacheType.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/cache/InMemoryCacheConfigurator.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/cache/InMemoryCacheManager.java
- apl-utils/src/test/java/com/apollocurrency/aplwallet/apl/util/cache/InMemoryCacheManagerTest.java
- pom.xml
Implemented unified cache subsystem. (Without visualization of cache statistics);
increased the guava version up to 28.0;
> Apl 833 implement unified cache service on node

- pom.xml
point release 4.3.1 has several bug fixes
> update of resteasy and jackson versions to current

- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/TestBase.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/TestBaseOld.java
fix sendMoney to Vault Wallet if not enough balance
add sendMoney transactions to receive PublicKey on tested Accounts
> Added precondition before Tests

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/DexController.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/exchange/model/EthStationGasInfo.java
Add this fix to the develop branch.
> APL-988 get gas info values is not integer.

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/db/dao/mapper/MinMaxValueMapper.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/db/derived/DerivedDbTable.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/shard/ShardConstants.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/shard/ShardEngineImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/shard/ShardImporter.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/shard/helper/CsvExporterImpl.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/shard/helper/CsvWriterReaderDerivedTablesTest.java
Add account_asset, account_currency sort by id
Fix minMaxValue for corner cases (Long.MIN_VALUE, Long.MAX_VALUE)
Speedup export of transaction_shard_index by using transaction id pagination
> Implement account_asset, account_currency sort by id

- apl-api/src/main/java/com/apollocurrency/aplwallet/api/dto/BlockchainState.java
- apl-api/src/main/java/com/apollocurrency/aplwallet/api/response/DexOrderResponse.java
- apl-api/src/main/java/com/apollocurrency/aplwallet/api/response/DexTradeInfoResponse.java
- apl-api/src/main/java/com/apollocurrency/aplwallet/api/response/EthGasInfoResponse.java
- apl-conf/src/main/resources/conf-tn2/apl-blockchain.properties
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/ITest.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/TestBaseNew.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/TestBaseOld.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/tests/TestDex.java
Get trading history for certain account
get gas prices for different tx speed
> Added Some New Dex Base Methods

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/eth/contracts/DexContract.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/AplException.java
(create order), backend doesn't show exception message.
> APL-1035 If we don't have enough money(eth) for a tx fee,

- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/ITest.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/TestBaseNew.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/TestBaseOld.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/Wallet.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/tests/Test2FA.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/tests/TestDex.java
- apl-integration-tests/src/test/resources/config.json
cancelOrder
createDexOrder
added new data in config.json
changed 2FA tests
> Added new dex tests

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/FileDownloadService.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/FileDownloader.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/FileInfoDownloader.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/shards/ShardsDownloadService.java
After-debug fixes: shard downloading works fine again
> events fix and other small fixes

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/AplCore.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/db/AplDbVersion.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/exchange/service/DexService.java
added new dex_offer index to speed up selecting overdue offers
> added overdue index to dex_offer table

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/BlockchainProcessorImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/ShardDownloadPresenceObserver.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/DownloadableFilesManager.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/shards/ShardPresentData.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/shard/ShardImporter.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/peer/DownloadableFilesManagerTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/shard/ShardImporterTest.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/task/DefaultTaskDispatcher.java
added importing optional prunable data
> added extracting additional archive files (prunable)

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/exchange/service/DexOrderProcessor.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/exchange/service/DexService.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/exchange/service/DexSmartContractService.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/Constants.java
New algo always guarantee, that swap initiator will have at least
2x time to approve money transfer
> Add dynamic time adjusting algorithm.

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/TrimService.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/shard/ShardEngineImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/shard/observer/ShardObserver.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/app/TrimServiceTest.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/ThreadUtils.java
lock that removed was waiting forever in sharding; in other cases this this method is not called directly
> dublication lock aquiring removed; mostly unused parameter removed

- apl-api/src/main/java/com/apollocurrency/aplwallet/api/dto/TaggedDataDTO.java
- apl-api/src/main/java/com/apollocurrency/aplwallet/api/response/AllTaggedDataResponse.java
- apl-api/src/main/java/com/apollocurrency/aplwallet/api/response/DataTagCountResponse.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/ITest.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/Parameters.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/RequestType.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/TestBaseNew.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/TestBaseOld.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/tests/TestTaggedData.java
added new class tagged DataDTO
added new class AllTaggedDataResponse
added new class DataTagCountResponse
added new methods
added TestTaggedData
> taggedData tests

- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/ITest.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/Parameters.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/RequestType.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/TestBaseNew.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/model/TestBaseOld.java
- apl-integration-tests/src/test/java/com/apollocurrrency/aplwallet/inttest/tests/TestTaggedData.java
searchTaggedData
extendTaggedData
> added new tests

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/DownloadableFilesManager.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/shard/ShardPrunableZipHashCalculator.java
> better logging for file info updates, fix of wrong file ID

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/BlockchainProcessorImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/FileDownloader.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/shards/ShardInfoDownloader.java
10 sec instead of 4sec waiting of initial peer connects;
2 attempts to connect to additional peers while getting ShardingInfo;
twice more attempts to get file chunk from peer
> Beter initial peer connectivity

- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/cls/BasicClassificator.java
- code is not used now, so resources releasing fix is not urgent
> added code for resource release

- apl-core/pom.xml
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/Helper2FA.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/DexTransactionSendingController.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/rest/exception/ConstraintViolationExceptionMapper.java
- apl-core/src/main/resources/META-INF/validation.xml
- pom.xml
- Drop deprecated resteasy validator, 
- Return latest core resteasy version, 
- add cdi hibernate validator,
- Add paranamer to extract actual parameter names
- Update exception mapper
> Validation dependencies enhancement

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/db/DataSourceWrapper.java
Given that a db in a new format (MV_STORE) requires either getting a full db file or updating a schema from version 0, it's absolutely safe to delete the updateTransactionTable method. (see AplDbVersion=>case 3=>sender_public_key BINARY(32))
> [NO_TICKET] Delete redundant updateTransactionTable

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/exchange/dao/DexOrderDao.java
quick fix for misplaced offset and limit
> SQL: correct place of limit and offset

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/API.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/AccountController.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/rest/exception/IllegalArgumentExceptionMapper.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/rest/utils/ResponseBuilder.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/AbstractEndpointTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/AccountControllerTest.java
APL-1372 added validation for assetId;
APL-1410 added validation for assetId;
APL-1403 added exception mapper for IllegalArgumentException;
> APL-1400 added validation for currencyId;

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/shards/ShardInfoDownloader.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/shards/ShardsDownloadService.java
Situation is: we do not have good shards on TN 2 from 1 to 10, only shard 11 and others. So nbow code handles such configuration
> NPE in shard download fixed

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/account/service/AccountAssetServiceImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/TrimService.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/db/derived/BasicDbTable.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/JSONData.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/order/dao/OrderTable.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/order/entity/AskOrder.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/order/entity/BidOrder.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/order/entity/Order.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/order/service/OrderMatchService.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/order/service/OrderService.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/order/service/impl/AskOrderServiceImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/order/service/impl/BidOrderServiceImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/order/service/impl/OrderMatchServiceImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/trade/entity/Trade.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/trade/service/TradeService.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/trade/service/impl/TradeServiceImpl.java
- apl-exec/src/main/resources/logback.xml
- bug fix of ask / bid order processing
- trade entity processing
> Bugfix/ask-bid order, trade code update

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/shard/ShardMigrationExecutor.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/shard/ShardService.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/shard/helper/SecondaryIndexInsertHelper.java
- removed dropping indexes on shard creation
- added a bit logging
> removed code for dropping indexes after switching to MVStore engine

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/get/GetAliases.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/get/GetAliasesLike.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/state/AliasService.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/state/impl/AliasServiceImpl.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/service/state/impl/AliasServiceTest.java
Converted DbIterator to Stream did not close db connection after usage
> Fix db connection leak for GetAliases api

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/dao/state/phasing/PhasingPollLinkedTransactionTable.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/dao/state/phasing/PhasingPollTable.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/Blockchain.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/BlockchainImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/state/impl/PhasingPollServiceImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/transaction/messages/update/UpdateAttachment.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/dao/state/phasing/PhasingPollLinkedTransactionTest.java
1. Rename UpdateAttachment `version` field to `updateVersion`
2. Eliminate Blockchain component usage inside Phasing derived tables
> Move blockchain to service level for phasing dao

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/AplCore.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/GenesisAccounts.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/GenesisImportException.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/GenesisImporter.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/GenesisImporterProducer.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/observer/ShardDownloadPresenceObserver.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/app/GenesisImporterTest.java
- apl-exec/src/main/java/com/apollocurrency/aplwallet/apl/exec/Apollo.java
- apl-exec/src/main/java/com/apollocurrency/aplwallet/apl/exec/CmdLineArgs.java
- apl-exec/src/main/resources/logback.xml
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/env/config/ResourceLocator.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/env/config/UserResourceLocator.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/env/dirprovider/ConfigDirProvider.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/env/dirprovider/ConfigDirProviderFactory.java
fixed importing the genesis block from config dir by chainId;
> APL-1679 added ResourceLocator;

- apl-api/src/main/java/com/apollocurrency/aplwallet/api/p2p/request/ShardingInfoRequest.java
fixed object mapping with no args constructor
> Fix of shard info p2p request

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/BlockchainProcessorImpl.java
fixed block download error after importing shard archive
> bug fix for blockchain download after shard archive import

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/shard/observer/ShardObserver.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/shard/observer/ShardObserverTest.java
- apl-core/src/test/resources/conf/tn2-shard-observer-config.json
added edge logic with frequency division
> shard height computing fix

- apl-api2/pom.xml
- apl-exec/packaging/pkg-apollo-blockchain.json
fixed swagger codegen issue on windows;
> [N_TICKET] fixed swagger codegen issue on windows;

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeerHttpServer.java
- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/env/dirprovider/DefaultConfigDirProvider.java
Start is fixed with no command line parameters; Behavior of UPnP in case of
buggy router is fixed (router can not map ports)
> Start is fixed with no command line parameters; Behavior of UPnP fixed

- apl-api/src/main/java/com/apollocurrency/aplwallet/api/p2p/request/BaseP2PRequest.java
- apl-api/src/main/java/com/apollocurrency/aplwallet/api/p2p/request/FileChunkRequest.java
- apl-api/src/main/java/com/apollocurrency/aplwallet/api/p2p/request/FileDownloadInfoRequest.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/FileInfoDownloader.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/statcheck/PeerInfoStatistics.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/statcheck/PeerValidityDecisionMaker.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/files/statcheck/PeersList.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/blockchain/TransactionProcessorImpl.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/api/p2p/request/FileDownloadInfoRequestTest.java
- apl-exec/src/main/resources/logback.xml
Fix json serialization of FileDownloadInfoRequest
> APL-1768 shard download NO_PEERS fix

- apl-utils/src/main/java/com/apollocurrency/aplwallet/apl/util/env/dirprovider/ServiceModeDirProvider.java
moved from apollo-blockchain to ApolloWallet base dir
> DB, logs, secure wallet and vault wallet data dirs moved one level up

- apl-conf/src/main/resources/conf-tn1/apl-blockchain.properties
- apl-conf/src/main/resources/conf-tn2/apl-blockchain.properties
- apl-conf/src/main/resources/conf-tn3/apl-blockchain.properties
- apl-conf/src/main/resources/conf/apl-blockchain.properties
Changed the database default user name and port;
> [NO_TICKET] changed default db user name;

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/GetMorePeersThread.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeerConnectingThread.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeerDb.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeerLoaderThread.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/peer/PeersService.java
Removed static calls to PeerDb component
> PeerDb changes, removed static methods and initialization

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/fulltext/DbUtils.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/fulltext/FullTextSearchServiceImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/state/account/impl/AccountInfoServiceImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/state/asset/impl/AssetServiceImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/state/currency/impl/CurrencyServiceImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/state/impl/DGSServiceImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/state/impl/PollServiceImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/state/impl/TaggedDataServiceImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/shard/helper/AbstractHelper.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/shard/helper/csv/CsvWriterImpl.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/shard/helper/CsvImporterTest.java
- apl-updater/src/main/java/com/apollocurrency/aplwallet/apl/updater/repository/UpdaterDbRepository.java
auto-releasing resources in try-catch blocks
> release ResultSet resources in try block

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/blockchain/TransactionBuilderFactory.java
Fix NPE during id verification
> APL-1888 - Fix legacy json transaction id verification after deserialization

- apl-exec/src/main/java/com/apollocurrency/aplwallet/apl/exec/Apollo.java
- apl-exec/src/main/java/com/apollocurrency/aplwallet/apl/exec/LogDirPropertyDefiner.java
- apl-exec/src/main/java/com/apollocurrency/aplwallet/apl/exec/MariaDbProcess.java
- apl-exec/src/main/resources/logback.xml
MaridbProcess logs will be written into the apl-blockchain-logs dir
> APL-1934 Replace current working dir by the apl-blockchain-logs dir for the MariaDbProcess log output

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/BlockEventSourceProcessor.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/get/GetAccount.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/get/GetAccountCurrencies.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/http/get/GetCurrencyAccounts.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/AccountController.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/state/account/AccountCurrencyService.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/state/account/impl/AccountCurrencyServiceImpl.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/state/currency/impl/CurrencyServiceImpl.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/AccountControllerTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/service/state/currency/CurrencyServiceTest.java
> APL-1975 Fix currency deletion

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/service/state/currency/impl/CurrencyServiceImpl.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/service/state/currency/CurrencyServiceTest.java
> APL-1984 - Fix currency issuance compatibility

- apl-conf/src/main/resources/conf-tn2/apl-blockchain.properties
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/app/GenesisImporter.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/dao/state/derived/FullyCachedTable.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/app/GenesisImporterTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/dao/prunable/PrunableMessageTableTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/dao/state/derived/DerivedDbTableListingTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/dao/state/derived/FullyCachedTableTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/db/EntityDbTableTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/db/ValuesDbTableTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/service/state/impl/DGSObserverTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/service/state/impl/DGSServiceSearchTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/service/state/impl/DGSServiceTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/shard/helper/CsvExporterTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/shard/helper/CsvWriterReaderDerivedTablesTest.java
- apl-db-updater/src/main/resources/db/migration/apl/V1_0__Initialize_tables.sql
- apl-db-updater/src/main/resources/db/migration/shard/V1_0__Initialize_tables.sql
Fix db tests, get back genesis accounts/publicKeys number validation
Remove each table explicit collation/charset/engine
[Changes reviewed on CodeStream](https://api.codestream.com/r/YJQEr_F-aATlXG_8/QMVpq0-7TUyrow_Tqe6CoQ?src=GitHub) by ylarin, alzinchenko on Jun 10, 2021
> APL-1884 - Code improvements

- apl-exec/src/main/resources/logback.xml
> APL-2075 - Add inMemory logging appender for GetLog API

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/rest/service/DexOrderAttachmentFactory.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/transaction/messages/DexOrderAttachment.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/transaction/messages/DexOrderAttachmentV2.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/transaction/messages/DexOrderAttachmentTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/transaction/messages/DexOrderAttachmentV2Test.java
> APL-2083 - Fix dexOrder v2 version verification

- apl-api/src/main/java/com/apollocurrency/aplwallet/api/dto/vault/UserKeyStoreDTO.java
- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/KeyStoreController.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/KeyStoreControllerTest.java
> APL-2094 - Keystore export passphrase param compatibility

- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/dao/state/smc/SmcContractEventLogTableTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/dao/state/smc/SmcContractMappingTableTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/dao/state/smc/SmcContractStateTableTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/dao/state/smc/SmcContractTableTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/transaction/types/smc/AbstractSmcTransactionTypeApplyTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/core/transaction/types/smc/SmcPublishContractTransactionTypeApplyTest.java
- apl-core/src/test/java/com/apollocurrency/aplwallet/apl/data/DbTestData.java
- apl-core/src/test/resources/db/smc-data.sql
- apl-core/src/test/resources/db/smc_event-data.sql
- apl-core/src/test/resources/db/smc_mapping-data.sql
> fixed smc tests;

- apl-conf/src/main/resources/conf-tn2/chains.json
* Set sharding frequency to every 200 blocks starting from 201000 height
> APL-2142 - Speedup sharding tn2

- README.md
Added description how to install additional 'Graal.js' component used by SmartContract subsystem
> updated README.md with installation of additional Graal.js component

- apl-core/src/main/java/com/apollocurrency/aplwallet/apl/core/rest/endpoint/KeyStoreController.java
Fix for Jetty error - IllegalStateException: No multipart config for servlet
> Vault Wallet file importing error

- apl-conf/src/main/resources/conf-tn2/chains.json
- apl-dex/pom.xml
The web3j.core version is taken from Apollo-bom-ext
> web3j.core is bumped to 5.0.0 in bom
